[[constraint]]
  name = "github.com/hashicorp/packer"
  version = "1.1.3"

[[constraint]]
  name = "github.com/hetznercloud/hcloud-go"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/multistep"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
